# Generated by Django 3.0.3 on 2020-06-12 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(default='abc', max_length=100)),
                ('lastName', models.CharField(default='xyz', max_length=100)),
                ('dob', models.DateField()),
                ('email', models.EmailField(default='abc@xyz.com', max_length=254)),
                ('phone', models.IntegerField(default=123)),
                ('organization', models.CharField(blank=True, max_length=200, null=True)),
                ('msg', models.TextField(blank=True, max_length=1000, null=True)),
                ('idProof', models.FileField(upload_to='proofs/')),
                ('condition', models.BooleanField(default=False)),
            ],
        ),
    ]
