# Generated by Django 3.0.3 on 2020-06-12 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataDetails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='members',
            name='idProof',
            field=models.ImageField(upload_to='proofs/'),
        ),
    ]
