# Generated by Django 3.0.3 on 2020-06-13 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataDetails', '0002_auto_20200612_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='members',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
