# Generated by Django 3.0.3 on 2020-06-14 13:58

import dataDetails.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataDetails', '0004_event_galleryimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='date',
        ),
        migrations.AddField(
            model_name='event',
            name='eventDate',
            field=models.DateField(default='2020-02-12'),
        ),
        migrations.AlterField(
            model_name='galleryimages',
            name='image',
            field=models.ImageField(upload_to=dataDetails.models.get_image),
        ),
    ]
