# Generated by Django 3.0.3 on 2020-06-15 05:08

import dataDetails.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataDetails', '0005_auto_20200614_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(default='njwnj.jpg', upload_to=dataDetails.models.get_image),
        ),
        migrations.DeleteModel(
            name='galleryImages',
        ),
    ]
