# Generated by Django 3.0.3 on 2020-06-15 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataDetails', '0006_auto_20200615_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video',
            field=models.CharField(default='fnnfedf.mp4', max_length=250),
            preserve_default=False,
        ),
    ]
