# Generated by Django 3.0.3 on 2020-06-15 06:06

import dataDetails.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataDetails', '0007_event_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='image',
        ),
        migrations.RemoveField(
            model_name='event',
            name='video',
        ),
        migrations.CreateModel(
            name='eventVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.CharField(max_length=250)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataDetails.event')),
            ],
        ),
        migrations.CreateModel(
            name='eventImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='abc.jpg', upload_to=dataDetails.models.get_image)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataDetails.event')),
            ],
        ),
    ]
