# Generated by Django 3.0.3 on 2020-06-16 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataDetails', '0008_auto_20200615_1136'),
    ]

    operations = [
        migrations.CreateModel(
            name='notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_published', models.DateField(default='2020-02-20')),
                ('title', models.CharField(max_length=250)),
                ('image', models.ImageField(blank=True, null=True, upload_to='notices/')),
                ('msg', models.TextField()),
                ('author', models.CharField(max_length=250)),
            ],
        ),
    ]
