# Generated by Django 3.0.3 on 2020-06-16 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataDetails', '0009_notice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notice',
            old_name='date_published',
            new_name='datePublished',
        ),
    ]
